# File: .github/workflows/setup-node/action.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies ⚡
        id: cache_dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies 🔧
        run: npm ci

      - name: Build
        run: npm run build