on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.npm
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        continue-on-error: false  # Add this to continue even if there's an error here

      - name: Check npm version
        run: npm --version

      - name: Run build
        run: npm run build
        continue-on-error: false  # Add this to continue even if there's an error here

      - name: Print Environment Variables
        run: printenv  # Helps in debugging environment issues